# Generated by Django 6.0.1 on 2026-01-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'password',
                    models.CharField(max_length=128, verbose_name='password'),
                ),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        max_length=255, unique=True, verbose_name='E-mail'
                    ),
                ),
                (
                    'first_name',
                    models.CharField(max_length=255, verbose_name='Имя'),
                ),
                (
                    'middle_name',
                    models.CharField(
                        blank=True, max_length=255, verbose_name='Отчество'
                    ),
                ),
                (
                    'last_name',
                    models.CharField(max_length=255, verbose_name='Фамилия'),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, verbose_name='Активен'),
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False, verbose_name='Сотрудник'
                    ),
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False, verbose_name='Суперпользователь'
                    ),
                ),
                (
                    'date_joined',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
