# Generated by Django 6.0.1 on 2026-01-17 02:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BusinessElement',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255, unique=True, verbose_name='Название'
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name='Описание',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Бизнес-элемент',
                'verbose_name_plural': 'Бизнес-элементы',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255, unique=True, verbose_name='Название'
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name='Описание',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='AccessRoleRule',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'read_permission',
                    models.BooleanField(
                        default=False, verbose_name='Чтение (свои)'
                    ),
                ),
                (
                    'read_all_permission',
                    models.BooleanField(
                        default=False, verbose_name='Чтение (все)'
                    ),
                ),
                (
                    'create_permission',
                    models.BooleanField(
                        default=False, verbose_name='Создание'
                    ),
                ),
                (
                    'update_permission',
                    models.BooleanField(
                        default=False, verbose_name='Обновление (свои)'
                    ),
                ),
                (
                    'update_all_permission',
                    models.BooleanField(
                        default=False, verbose_name='Обновление (все)'
                    ),
                ),
                (
                    'delete_permission',
                    models.BooleanField(
                        default=False, verbose_name='Удаление (свои)'
                    ),
                ),
                (
                    'delete_all_permission',
                    models.BooleanField(
                        default=False, verbose_name='Удаление (все)'
                    ),
                ),
                (
                    'element',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='rbac.businesselement',
                        verbose_name='Бизнес-элемент',
                    ),
                ),
                (
                    'role',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='rbac.role',
                        verbose_name='Роль',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Правило доступа',
                'verbose_name_plural': 'Правила доступа',
                'unique_together': {('role', 'element')},
            },
        ),
    ]
